### ISSUE TITLE
"How long until this?" command/info

### ISSUE THREAD

**Issue by towerofnix** [theZacAttacks/RemindMeBot#9]
I live in the timezone ADT. I set a reminder for "17:30 PST". According to google the present time in PST is ~14:00, so I know I have to wait three and a half hours. I think it would be handy if the bot could tell me this itself.

Just putting the info on how long it'll be until the reminder hits in the "I'll try to remind you then!" message would be really handy in itself, but a fun extra tool would be a command telling you how long it'll be at the present time.

**Comment by compufox** [comment]
sorry for the long delay

this was just added in 2811c03

reply to the receipt with !until and it will say how many hours/minutes until your reminder

**Comment by towerofnix** [comment]
Thank you - this is very neat! :tada:
